### ISSUE TITLE
indexWinners script gets dropped by remote peer and doesn't capture results

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/tools#74]
At some point the `indexWinners` script gets dropped from the connection to the RPC node and exits without capturing results:

```
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
2021-05-16 18:50:17        API/INIT: Health keepalive check failed: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
Oops at: 1621183817349
Error: disconnected from wss://bp-rpc-1.zeitgeist.pm: 1006:: Connection dropped by remote peer.
    at W3CWebSocket.value [as onclose] (/Users/logansaether/Code/zeitgeistpm/tools/node_modules/@polkadot/rpc-provider/ws/index.cjs:176:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/logansaether/Code/zeitgeistpm/tools/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/Users/logansaether/Code/zeitgeistpm/tools/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/Users/logansaether/Code/zeitgeistpm/tools/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:467:12)
    at WebSocketConnection.handleSocketClose (/Users/logansaether/Code/zeitgeistpm/tools/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at net.js:673:12
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It should be able to gracefully handle connection being dropped and either capture partial results, or wait and attempt a reconnection to finish execution.

**Comment by morkeltry** [comment]
Can you give me an idea of the context?
All the errors look like this, it's not necessarily that the node chose to drop the connection.

**Comment by morkeltry** [comment]
[PR 73](https://github.com/zeitgeistpm/tools/pull/73) fixes this by chunking RPC requests and not sending further requests from the same function until chunks complete.
Although the connection is a websocket and so the concurrent requests are not actually concurrent connections, this seems to work, so so assumedly the remote RPC server is counting and limiting concurrent requests in a similar way to if they were concurrent connections.
